import turtle
turtle.Turtle()
turtle.pensize(4)
turtle.up()
turtle.forward(180)
turtle.right(90)
turtle.forward(200)
#angolo in basso a destra
#disegna il perimetro della griglia 
turtle.down()
turtle.right(90)
turtle.forward(360)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(360)
turtle.right(90)
turtle.forward(400)
turtle.right(90) #angolo iniziale
#disegna la griglia vera e propria
turtle.forward(120)
turtle.right(90)
turtle.forward(400)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(120)
#disegna seconda griglia
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(360)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(360)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(360)
turtle.left(90)
turtle.forward(100) #angolo in alto a destra, punta verso su
#animazione
